# Build Pre Release workflow for generating a pre-release build of the plugin.

name: Build Pre Release

on:
  # Trigger this workflow when a pre-release is published.
  release:
    types:
      - prereleased

concurrency:
  # Ensure only one workflow runs per release tag and cancel any in-progress workflows for the same group.
  group: ${{ github.workflow }}-${{ github.event.release.tag_name }}
  cancel-in-progress: true

jobs:
  build:
    # Use the latest Ubuntu runner for executing the job.
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code at the version corresponding to the release event.
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment with the specified version (16.13.2) for the build process.
      - name: Setup Node.js 16.13.2
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"

      # Step 3: Install all npm dependencies required for building the plugin.
      - name: Install npm dependencies
        run: npm install

      # Step 4: Build the production-ready version of the plugin using the npm `prod` script.
      - name: Build plugin
        run: npm run prod

      # Step 5: Move the build output directory `__build/directorist` to the root level for further processing.
      - name: Move directorist to root
        run: mv __build/directorist ./directorist

      # Step 6: Create a zip archive of the plugin build, naming it with the release tag for easier identification.
      - name: Create zip file
        run: |
          tag_name=$(git describe --tags --abbrev=0)
          zip -r "directorist.${tag_name}.zip" directorist

      # Step 7: Upload the generated zip file as an asset to the pre-release on GitHub.
      - name: Upload zip file as a release asset
        uses: softprops/action-gh-release@v1
        with:
          files: directorist*.zip
        env:
          # Use the GitHub token for authentication when uploading assets.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}